package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * AcdmExtnlUser generated by hbm2java
 */
public class AcdmExtnlUser  implements java.io.Serializable {


     private BigDecimal id;
     private String userOwnrId;
     private String userName;
     private String userEmailId;
     private String libGrp;

    public AcdmExtnlUser() {
    }

	
    public AcdmExtnlUser(BigDecimal id) {
        this.id = id;
    }
    public AcdmExtnlUser(BigDecimal id, String userOwnrId, String userName, String userEmailId, String libGrp) {
       this.id = id;
       this.userOwnrId = userOwnrId;
       this.userName = userName;
       this.userEmailId = userEmailId;
       this.libGrp = libGrp;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getUserOwnrId() {
        return this.userOwnrId;
    }
    
    public void setUserOwnrId(String userOwnrId) {
        this.userOwnrId = userOwnrId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserEmailId() {
        return this.userEmailId;
    }
    
    public void setUserEmailId(String userEmailId) {
        this.userEmailId = userEmailId;
    }
    public String getLibGrp() {
        return this.libGrp;
    }
    
    public void setLibGrp(String libGrp) {
        this.libGrp = libGrp;
    }




}


