package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AcdmListTp generated by hbm2java
 */
public class AcdmListTp  implements java.io.Serializable {


     private String listTpId;
     private String listTpDn;
     private String listStDn;
     private String listTp;
     private Set<AcdmList> acdmLists = new HashSet<AcdmList>(0);

    public AcdmListTp() {
    }

	
    public AcdmListTp(String listTpId) {
        this.listTpId = listTpId;
    }
    public AcdmListTp(String listTpId, String listTpDn, String listStDn, String listTp, Set<AcdmList> acdmLists) {
       this.listTpId = listTpId;
       this.listTpDn = listTpDn;
       this.listStDn = listStDn;
       this.listTp = listTp;
       this.acdmLists = acdmLists;
    }
   
    public String getListTpId() {
        return this.listTpId;
    }
    
    public void setListTpId(String listTpId) {
        this.listTpId = listTpId;
    }
    public String getListTpDn() {
        return this.listTpDn;
    }
    
    public void setListTpDn(String listTpDn) {
        this.listTpDn = listTpDn;
    }
    public String getListStDn() {
        return this.listStDn;
    }
    
    public void setListStDn(String listStDn) {
        this.listStDn = listStDn;
    }
    public String getListTp() {
        return this.listTp;
    }
    
    public void setListTp(String listTp) {
        this.listTp = listTp;
    }
    public Set<AcdmList> getAcdmLists() {
        return this.acdmLists;
    }
    
    public void setAcdmLists(Set<AcdmList> acdmLists) {
        this.acdmLists = acdmLists;
    }




}


