package com.ibg.selectionrecords.pojo;

// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * AcdmList generated by hbm2java
 */
public class AcdmList {

	private BigDecimal listId; // List ID
	private String acdmListTp;
	private String userOwnrId;// User ID
	private String active;
	private BigDecimal daysHistoryStored; // Days History Stored
	private String description; // List Name
	private String notificationEmail;// Notification Email Addresses
	private String notificationEmailDetailed;// Notification Detailed Email
	private BigDecimal notificationEmailType;// Notification Email Type
	private String notificationSchedule;// Notification Schedule
	private String oldUdId;
	private String forwardList;// Forward List
	private String libGrp;

	public AcdmList() {
	}

	public AcdmList(BigDecimal listId) {
		this.listId = listId;
	}

	public BigDecimal getListId() {
		return this.listId;
	}

	public void setListId(BigDecimal listId) {
		this.listId = listId;
	}

	public String getAcdmListTp() {
		return this.acdmListTp;
	}

	public void setAcdmListTp(String acdmListTp) {
		this.acdmListTp = acdmListTp;
	}

	public String getUserOwnrId() {
		return this.userOwnrId;
	}

	public void setUserOwnrId(String userOwnrId) {
		this.userOwnrId = userOwnrId;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public BigDecimal getDaysHistoryStored() {
		return this.daysHistoryStored;
	}

	public void setDaysHistoryStored(BigDecimal daysHistoryStored) {
		this.daysHistoryStored = daysHistoryStored;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNotificationEmail() {
		return this.notificationEmail;
	}

	public void setNotificationEmail(String notificationEmail) {
		this.notificationEmail = notificationEmail;
	}

	public String getNotificationEmailDetailed() {
		return this.notificationEmailDetailed;
	}

	public void setNotificationEmailDetailed(String notificationEmailDetailed) {
		this.notificationEmailDetailed = notificationEmailDetailed;
	}

	public BigDecimal getNotificationEmailType() {
		return this.notificationEmailType;
	}

	public void setNotificationEmailType(BigDecimal notificationEmailType) {
		this.notificationEmailType = notificationEmailType;
	}

	public String getNotificationSchedule() {
		return this.notificationSchedule;
	}

	public void setNotificationSchedule(String notificationSchedule) {
		this.notificationSchedule = notificationSchedule;
	}

	public String getOldUdId() {
		return this.oldUdId;
	}

	public void setOldUdId(String oldUdId) {
		this.oldUdId = oldUdId;
	}

	public String getForwardList() {
		return this.forwardList;
	}

	public void setForwardList(String forwardList) {
		this.forwardList = forwardList;
	}

	public String getLibGrp() {
		return this.libGrp;
	}

	public void setLibGrp(String libGrp) {
		this.libGrp = libGrp;
	}

}
