package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * AcdmOriginalOrderInfo generated by hbm2java
 */
public class AcdmOriginalOrderInfo  implements java.io.Serializable {


     private BigDecimal oprId;
     private CisUser cisUser;
     private AcdmList acdmList;
     private String title;
     private String author;
     private String publisher;
     private String pubyear;
     private String edition;
     private String partno;
     private String format;
     private String price;
     private String currency;
     private String volume;

    public AcdmOriginalOrderInfo() {
    }

	
    public AcdmOriginalOrderInfo(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public AcdmOriginalOrderInfo(BigDecimal oprId, CisUser cisUser, AcdmList acdmList, String title, String author, String publisher, String pubyear, String edition, String partno, String format, String price, String currency, String volume) {
       this.oprId = oprId;
       this.cisUser = cisUser;
       this.acdmList = acdmList;
       this.title = title;
       this.author = author;
       this.publisher = publisher;
       this.pubyear = pubyear;
       this.edition = edition;
       this.partno = partno;
       this.format = format;
       this.price = price;
       this.currency = currency;
       this.volume = volume;
    }
   
    public BigDecimal getOprId() {
        return this.oprId;
    }
    
    public void setOprId(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public CisUser getCisUser() {
        return this.cisUser;
    }
    
    public void setCisUser(CisUser cisUser) {
        this.cisUser = cisUser;
    }
    public AcdmList getAcdmList() {
        return this.acdmList;
    }
    
    public void setAcdmList(AcdmList acdmList) {
        this.acdmList = acdmList;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getPubyear() {
        return this.pubyear;
    }
    
    public void setPubyear(String pubyear) {
        this.pubyear = pubyear;
    }
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }
    public String getPartno() {
        return this.partno;
    }
    
    public void setPartno(String partno) {
        this.partno = partno;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getVolume() {
        return this.volume;
    }
    
    public void setVolume(String volume) {
        this.volume = volume;
    }




}


