package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * AcdmItemHistory generated by hbm2java
 */
public class AcdmItemHistory  implements java.io.Serializable {


     private BigDecimal histId;
     private BigDecimal oprId;
     private BigDecimal srcOprId;
     private BigDecimal srcListId;
     private BigDecimal destListId;
     private String ean;
     private String event;
     private BigDecimal pathId;
     private Serializable dateTime;
     private String details;
     private String eventInitiatorId;

    public AcdmItemHistory() {
    }

	
    public AcdmItemHistory(BigDecimal histId) {
        this.histId = histId;
    }
    public AcdmItemHistory(BigDecimal histId, BigDecimal oprId, BigDecimal srcOprId, BigDecimal srcListId, BigDecimal destListId, String ean, String event, BigDecimal pathId, Serializable dateTime, String details, String eventInitiatorId) {
       this.histId = histId;
       this.oprId = oprId;
       this.srcOprId = srcOprId;
       this.srcListId = srcListId;
       this.destListId = destListId;
       this.ean = ean;
       this.event = event;
       this.pathId = pathId;
       this.dateTime = dateTime;
       this.details = details;
       this.eventInitiatorId = eventInitiatorId;
    }
   
    public BigDecimal getHistId() {
        return this.histId;
    }
    
    public void setHistId(BigDecimal histId) {
        this.histId = histId;
    }
    public BigDecimal getOprId() {
        return this.oprId;
    }
    
    public void setOprId(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public BigDecimal getSrcOprId() {
        return this.srcOprId;
    }
    
    public void setSrcOprId(BigDecimal srcOprId) {
        this.srcOprId = srcOprId;
    }
    public BigDecimal getSrcListId() {
        return this.srcListId;
    }
    
    public void setSrcListId(BigDecimal srcListId) {
        this.srcListId = srcListId;
    }
    public BigDecimal getDestListId() {
        return this.destListId;
    }
    
    public void setDestListId(BigDecimal destListId) {
        this.destListId = destListId;
    }
    public String getEan() {
        return this.ean;
    }
    
    public void setEan(String ean) {
        this.ean = ean;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }
    public BigDecimal getPathId() {
        return this.pathId;
    }
    
    public void setPathId(BigDecimal pathId) {
        this.pathId = pathId;
    }
    public Serializable getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Serializable dateTime) {
        this.dateTime = dateTime;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getEventInitiatorId() {
        return this.eventInitiatorId;
    }
    
    public void setEventInitiatorId(String eventInitiatorId) {
        this.eventInitiatorId = eventInitiatorId;
    }




}


