package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * AcdmExternalPartReservation generated by hbm2java
 */
public class AcdmExternalPartReservation  implements java.io.Serializable {


     private BigDecimal oprId;
     private CisUser cisUser;
     private AcdmList acdmList;
     private BigDecimal sku;
     private String active;
     private String description;
     private Integer price;
     private Blob priceNotes;
     private Blob details;
     private Integer alibrisSellPrice;
     private String condition;
     private String publisher;
     private String supplierId;
     private String sellerId;
     private String sellerName;
     private String sellerReliability;
     private String shipsFrom;
     private Integer sellingPrice;
     private String sellingCurrency;

    public AcdmExternalPartReservation() {
    }

	
    public AcdmExternalPartReservation(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public AcdmExternalPartReservation(BigDecimal oprId, CisUser cisUser, AcdmList acdmList, BigDecimal sku, String active, String description, Integer price, Blob priceNotes, Blob details, Integer alibrisSellPrice, String condition, String publisher, String supplierId, String sellerId, String sellerName, String sellerReliability, String shipsFrom, Integer sellingPrice, String sellingCurrency) {
       this.oprId = oprId;
       this.cisUser = cisUser;
       this.acdmList = acdmList;
       this.sku = sku;
       this.active = active;
       this.description = description;
       this.price = price;
       this.priceNotes = priceNotes;
       this.details = details;
       this.alibrisSellPrice = alibrisSellPrice;
       this.condition = condition;
       this.publisher = publisher;
       this.supplierId = supplierId;
       this.sellerId = sellerId;
       this.sellerName = sellerName;
       this.sellerReliability = sellerReliability;
       this.shipsFrom = shipsFrom;
       this.sellingPrice = sellingPrice;
       this.sellingCurrency = sellingCurrency;
    }
   
    public BigDecimal getOprId() {
        return this.oprId;
    }
    
    public void setOprId(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public CisUser getCisUser() {
        return this.cisUser;
    }
    
    public void setCisUser(CisUser cisUser) {
        this.cisUser = cisUser;
    }
    public AcdmList getAcdmList() {
        return this.acdmList;
    }
    
    public void setAcdmList(AcdmList acdmList) {
        this.acdmList = acdmList;
    }
    public BigDecimal getSku() {
        return this.sku;
    }
    
    public void setSku(BigDecimal sku) {
        this.sku = sku;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Blob getPriceNotes() {
        return this.priceNotes;
    }
    
    public void setPriceNotes(Blob priceNotes) {
        this.priceNotes = priceNotes;
    }
    public Blob getDetails() {
        return this.details;
    }
    
    public void setDetails(Blob details) {
        this.details = details;
    }
    public Integer getAlibrisSellPrice() {
        return this.alibrisSellPrice;
    }
    
    public void setAlibrisSellPrice(Integer alibrisSellPrice) {
        this.alibrisSellPrice = alibrisSellPrice;
    }
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }
    public String getSellerId() {
        return this.sellerId;
    }
    
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }
    public String getSellerName() {
        return this.sellerName;
    }
    
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }
    public String getSellerReliability() {
        return this.sellerReliability;
    }
    
    public void setSellerReliability(String sellerReliability) {
        this.sellerReliability = sellerReliability;
    }
    public String getShipsFrom() {
        return this.shipsFrom;
    }
    
    public void setShipsFrom(String shipsFrom) {
        this.shipsFrom = shipsFrom;
    }
    public Integer getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Integer sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public String getSellingCurrency() {
        return this.sellingCurrency;
    }
    
    public void setSellingCurrency(String sellingCurrency) {
        this.sellingCurrency = sellingCurrency;
    }




}


