package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * AcdmListItem generated by hbm2java
 */
public class AcdmListItem  implements java.io.Serializable {


     private BigDecimal oprId;
     private BigDecimal listId;
     private BigDecimal ttlId;
     private String active;
     private BigDecimal srcListId;
     private String action;
     private Serializable dateCreated;
     private Serializable dateModified;
     private BigDecimal dateToExpire;
     private String expirationDate;
     private String failReason;
     private String approvalCenter;
     private String approvalPlan;
     private BigDecimal customer;
     private String ean;
     private String salesOrdDet;
     private BigDecimal suplr;
     private BigDecimal ratifierId;
     private BigDecimal selectorId;
     private BigDecimal reqId;
     private Serializable lastNotified;
     private Long quantity;
     private BigDecimal pathId;
     private String oididlist;
     private String internalNote;

    public AcdmListItem() {
    }

	
    public AcdmListItem(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public AcdmListItem(BigDecimal oprId, BigDecimal listId, BigDecimal ttlId, String active, BigDecimal srcListId, String action, Serializable dateCreated, Serializable dateModified, BigDecimal dateToExpire, String expirationDate, String failReason, String approvalCenter, String approvalPlan, BigDecimal customer, String ean, String salesOrdDet, BigDecimal suplr, BigDecimal ratifierId, BigDecimal selectorId, BigDecimal reqId, Serializable lastNotified, Long quantity, BigDecimal pathId, String oididlist, String internalNote) {
       this.oprId = oprId;
       this.listId = listId;
       this.ttlId = ttlId;
       this.active = active;
       this.srcListId = srcListId;
       this.action = action;
       this.dateCreated = dateCreated;
       this.dateModified = dateModified;
       this.dateToExpire = dateToExpire;
       this.expirationDate = expirationDate;
       this.failReason = failReason;
       this.approvalCenter = approvalCenter;
       this.approvalPlan = approvalPlan;
       this.customer = customer;
       this.ean = ean;
       this.salesOrdDet = salesOrdDet;
       this.suplr = suplr;
       this.ratifierId = ratifierId;
       this.selectorId = selectorId;
       this.reqId = reqId;
       this.lastNotified = lastNotified;
       this.quantity = quantity;
       this.pathId = pathId;
       this.oididlist = oididlist;
       this.internalNote = internalNote;
    }
   
    public BigDecimal getOprId() {
        return this.oprId;
    }
    
    public void setOprId(BigDecimal oprId) {
        this.oprId = oprId;
    }
    public BigDecimal getListId() {
        return this.listId;
    }
    
    public void setListId(BigDecimal listId) {
        this.listId = listId;
    }
    public BigDecimal getTtlId() {
        return this.ttlId;
    }
    
    public void setTtlId(BigDecimal ttlId) {
        this.ttlId = ttlId;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public BigDecimal getSrcListId() {
        return this.srcListId;
    }
    
    public void setSrcListId(BigDecimal srcListId) {
        this.srcListId = srcListId;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public Serializable getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Serializable dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Serializable getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Serializable dateModified) {
        this.dateModified = dateModified;
    }
    public BigDecimal getDateToExpire() {
        return this.dateToExpire;
    }
    
    public void setDateToExpire(BigDecimal dateToExpire) {
        this.dateToExpire = dateToExpire;
    }
    public String getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }
    public String getFailReason() {
        return this.failReason;
    }
    
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }
    public String getApprovalCenter() {
        return this.approvalCenter;
    }
    
    public void setApprovalCenter(String approvalCenter) {
        this.approvalCenter = approvalCenter;
    }
    public String getApprovalPlan() {
        return this.approvalPlan;
    }
    
    public void setApprovalPlan(String approvalPlan) {
        this.approvalPlan = approvalPlan;
    }
    public BigDecimal getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(BigDecimal customer) {
        this.customer = customer;
    }
    public String getEan() {
        return this.ean;
    }
    
    public void setEan(String ean) {
        this.ean = ean;
    }
    public String getSalesOrdDet() {
        return this.salesOrdDet;
    }
    
    public void setSalesOrdDet(String salesOrdDet) {
        this.salesOrdDet = salesOrdDet;
    }
    public BigDecimal getSuplr() {
        return this.suplr;
    }
    
    public void setSuplr(BigDecimal suplr) {
        this.suplr = suplr;
    }
    public BigDecimal getRatifierId() {
        return this.ratifierId;
    }
    
    public void setRatifierId(BigDecimal ratifierId) {
        this.ratifierId = ratifierId;
    }
    public BigDecimal getSelectorId() {
        return this.selectorId;
    }
    
    public void setSelectorId(BigDecimal selectorId) {
        this.selectorId = selectorId;
    }
    public BigDecimal getReqId() {
        return this.reqId;
    }
    
    public void setReqId(BigDecimal reqId) {
        this.reqId = reqId;
    }
    public Serializable getLastNotified() {
        return this.lastNotified;
    }
    
    public void setLastNotified(Serializable lastNotified) {
        this.lastNotified = lastNotified;
    }
    public Long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getPathId() {
        return this.pathId;
    }
    
    public void setPathId(BigDecimal pathId) {
        this.pathId = pathId;
    }
    public String getOididlist() {
        return this.oididlist;
    }
    
    public void setOididlist(String oididlist) {
        this.oididlist = oididlist;
    }
    public String getInternalNote() {
        return this.internalNote;
    }
    
    public void setInternalNote(String internalNote) {
        this.internalNote = internalNote;
    }




}


