package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA



/**
 * AcdmOrderInfoTemplateData generated by hbm2java
 */
public class AcdmOrderInfoTemplateData  implements java.io.Serializable {


     private AcdmOrderInfoTemplateDataId id;
     private AcdmOrderInfoTemplate acdmOrderInfoTemplate;
     private String fieldValue;

    public AcdmOrderInfoTemplateData() {
    }

	
    public AcdmOrderInfoTemplateData(AcdmOrderInfoTemplateDataId id, AcdmOrderInfoTemplate acdmOrderInfoTemplate) {
        this.id = id;
        this.acdmOrderInfoTemplate = acdmOrderInfoTemplate;
    }
    public AcdmOrderInfoTemplateData(AcdmOrderInfoTemplateDataId id, AcdmOrderInfoTemplate acdmOrderInfoTemplate, String fieldValue) {
       this.id = id;
       this.acdmOrderInfoTemplate = acdmOrderInfoTemplate;
       this.fieldValue = fieldValue;
    }
   
    public AcdmOrderInfoTemplateDataId getId() {
        return this.id;
    }
    
    public void setId(AcdmOrderInfoTemplateDataId id) {
        this.id = id;
    }
    public AcdmOrderInfoTemplate getAcdmOrderInfoTemplate() {
        return this.acdmOrderInfoTemplate;
    }
    
    public void setAcdmOrderInfoTemplate(AcdmOrderInfoTemplate acdmOrderInfoTemplate) {
        this.acdmOrderInfoTemplate = acdmOrderInfoTemplate;
    }
    public String getFieldValue() {
        return this.fieldValue;
    }
    
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }




}


