package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * AcdmOrderInfoTemplateDataId generated by hbm2java
 */
public class AcdmOrderInfoTemplateDataId  implements java.io.Serializable {


     private BigDecimal templateId;
     private String fieldKey;
     private BigDecimal lineNo;

    public AcdmOrderInfoTemplateDataId() {
    }

    public AcdmOrderInfoTemplateDataId(BigDecimal templateId, String fieldKey, BigDecimal lineNo) {
       this.templateId = templateId;
       this.fieldKey = fieldKey;
       this.lineNo = lineNo;
    }
   
    public BigDecimal getTemplateId() {
        return this.templateId;
    }
    
    public void setTemplateId(BigDecimal templateId) {
        this.templateId = templateId;
    }
    public String getFieldKey() {
        return this.fieldKey;
    }
    
    public void setFieldKey(String fieldKey) {
        this.fieldKey = fieldKey;
    }
    public BigDecimal getLineNo() {
        return this.lineNo;
    }
    
    public void setLineNo(BigDecimal lineNo) {
        this.lineNo = lineNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcdmOrderInfoTemplateDataId) ) return false;
		 AcdmOrderInfoTemplateDataId castOther = ( AcdmOrderInfoTemplateDataId ) other; 
         
		 return ( (this.getTemplateId()==castOther.getTemplateId()) || ( this.getTemplateId()!=null && castOther.getTemplateId()!=null && this.getTemplateId().equals(castOther.getTemplateId()) ) )
 && ( (this.getFieldKey()==castOther.getFieldKey()) || ( this.getFieldKey()!=null && castOther.getFieldKey()!=null && this.getFieldKey().equals(castOther.getFieldKey()) ) )
 && ( (this.getLineNo()==castOther.getLineNo()) || ( this.getLineNo()!=null && castOther.getLineNo()!=null && this.getLineNo().equals(castOther.getLineNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTemplateId() == null ? 0 : this.getTemplateId().hashCode() );
         result = 37 * result + ( getFieldKey() == null ? 0 : this.getFieldKey().hashCode() );
         result = 37 * result + ( getLineNo() == null ? 0 : this.getLineNo().hashCode() );
         return result;
   }   


}


