package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AcdmOrderInfoTemplate generated by hbm2java
 */
public class AcdmOrderInfoTemplate  implements java.io.Serializable {


     private BigDecimal templateId;
     private String templateName;
     private String userOwnerId;
     private String templateViewMode;
     private Set<AcdmOrderInfoTemplateData> acdmOrderInfoTemplateDatas = new HashSet<AcdmOrderInfoTemplateData>(0);

    public AcdmOrderInfoTemplate() {
    }

	
    public AcdmOrderInfoTemplate(BigDecimal templateId) {
        this.templateId = templateId;
    }
    public AcdmOrderInfoTemplate(BigDecimal templateId, String templateName, String userOwnerId, String templateViewMode, Set<AcdmOrderInfoTemplateData> acdmOrderInfoTemplateDatas) {
       this.templateId = templateId;
       this.templateName = templateName;
       this.userOwnerId = userOwnerId;
       this.templateViewMode = templateViewMode;
       this.acdmOrderInfoTemplateDatas = acdmOrderInfoTemplateDatas;
    }
   
    public BigDecimal getTemplateId() {
        return this.templateId;
    }
    
    public void setTemplateId(BigDecimal templateId) {
        this.templateId = templateId;
    }
    public String getTemplateName() {
        return this.templateName;
    }
    
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }
    public String getUserOwnerId() {
        return this.userOwnerId;
    }
    
    public void setUserOwnerId(String userOwnerId) {
        this.userOwnerId = userOwnerId;
    }
    public String getTemplateViewMode() {
        return this.templateViewMode;
    }
    
    public void setTemplateViewMode(String templateViewMode) {
        this.templateViewMode = templateViewMode;
    }
    public Set<AcdmOrderInfoTemplateData> getAcdmOrderInfoTemplateDatas() {
        return this.acdmOrderInfoTemplateDatas;
    }
    
    public void setAcdmOrderInfoTemplateDatas(Set<AcdmOrderInfoTemplateData> acdmOrderInfoTemplateDatas) {
        this.acdmOrderInfoTemplateDatas = acdmOrderInfoTemplateDatas;
    }




}


