package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AplcUser generated by hbm2java
 */
public class AplcUser  implements java.io.Serializable {


     private String userId;
     private String cnctFstNm;
     private String cnctLstNm;
     private String autoSysId;
     private String cnctOfflTtlNm;
     private String cnctPhNbr;
     private String cnctPhExtNbr;
     private String cnctPhFaxNbr;
     private String cnctPhAltNbr;
     private String addrInetDn;
     private String addrInetWebDn;
     private String lin1OptAddr;
     private String lin2OptAddr;
     private String lin3OptAddr;
     private String cityNm;
     private String stCd;
     private String zipCd;
     private String ctryIsoCd;
     private String userPwrdDn;
     private Date userPwrdLstUpdtDt;
     private String coNm;
     private Date userPwrdExprDt;
     private Date userAcssLstDt;
     private Date userAcssFstDt;
     private String addrInetLstDn;
     private String swInetDn;
     private String acctUserDfltId;
     private String userAddId;
     private Date addDt;
     private Date commUserAddDt;
     private Date commRtnDt;
     private String commRtnDn;
     private String userIiInd;
     private String srvcLvlAcssInd;
     private String lockInd;
     private Date lockDt;
     private String userLockLstId;
     private String lockDn;
     private String acctUserIiId;
     private String userIdUc;
     private BigDecimal cmaPrimRoleNbr;
     private String selListDupChkInd;
     private char dupChkInd;
     private String cisUserInd;
     private Set<CisUser> cisUsers = new HashSet<CisUser>(0);

    public AplcUser() {
    }

	
    public AplcUser(String userId, String userPwrdDn, String userIiInd, String srvcLvlAcssInd, String lockInd, String selListDupChkInd, char dupChkInd) {
        this.userId = userId;
        this.userPwrdDn = userPwrdDn;
        this.userIiInd = userIiInd;
        this.srvcLvlAcssInd = srvcLvlAcssInd;
        this.lockInd = lockInd;
        this.selListDupChkInd = selListDupChkInd;
        this.dupChkInd = dupChkInd;
    }
    public AplcUser(String userId, String cnctFstNm, String cnctLstNm, String autoSysId, String cnctOfflTtlNm, String cnctPhNbr, String cnctPhExtNbr, String cnctPhFaxNbr, String cnctPhAltNbr, String addrInetDn, String addrInetWebDn, String lin1OptAddr, String lin2OptAddr, String lin3OptAddr, String cityNm, String stCd, String zipCd, String ctryIsoCd, String userPwrdDn, Date userPwrdLstUpdtDt, String coNm, Date userPwrdExprDt, Date userAcssLstDt, Date userAcssFstDt, String addrInetLstDn, String swInetDn, String acctUserDfltId, String userAddId, Date addDt, Date commUserAddDt, Date commRtnDt, String commRtnDn, String userIiInd, String srvcLvlAcssInd, String lockInd, Date lockDt, String userLockLstId, String lockDn, String acctUserIiId, String userIdUc, BigDecimal cmaPrimRoleNbr, String selListDupChkInd, char dupChkInd, String cisUserInd, Set<CisUser> cisUsers) {
       this.userId = userId;
       this.cnctFstNm = cnctFstNm;
       this.cnctLstNm = cnctLstNm;
       this.autoSysId = autoSysId;
       this.cnctOfflTtlNm = cnctOfflTtlNm;
       this.cnctPhNbr = cnctPhNbr;
       this.cnctPhExtNbr = cnctPhExtNbr;
       this.cnctPhFaxNbr = cnctPhFaxNbr;
       this.cnctPhAltNbr = cnctPhAltNbr;
       this.addrInetDn = addrInetDn;
       this.addrInetWebDn = addrInetWebDn;
       this.lin1OptAddr = lin1OptAddr;
       this.lin2OptAddr = lin2OptAddr;
       this.lin3OptAddr = lin3OptAddr;
       this.cityNm = cityNm;
       this.stCd = stCd;
       this.zipCd = zipCd;
       this.ctryIsoCd = ctryIsoCd;
       this.userPwrdDn = userPwrdDn;
       this.userPwrdLstUpdtDt = userPwrdLstUpdtDt;
       this.coNm = coNm;
       this.userPwrdExprDt = userPwrdExprDt;
       this.userAcssLstDt = userAcssLstDt;
       this.userAcssFstDt = userAcssFstDt;
       this.addrInetLstDn = addrInetLstDn;
       this.swInetDn = swInetDn;
       this.acctUserDfltId = acctUserDfltId;
       this.userAddId = userAddId;
       this.addDt = addDt;
       this.commUserAddDt = commUserAddDt;
       this.commRtnDt = commRtnDt;
       this.commRtnDn = commRtnDn;
       this.userIiInd = userIiInd;
       this.srvcLvlAcssInd = srvcLvlAcssInd;
       this.lockInd = lockInd;
       this.lockDt = lockDt;
       this.userLockLstId = userLockLstId;
       this.lockDn = lockDn;
       this.acctUserIiId = acctUserIiId;
       this.userIdUc = userIdUc;
       this.cmaPrimRoleNbr = cmaPrimRoleNbr;
       this.selListDupChkInd = selListDupChkInd;
       this.dupChkInd = dupChkInd;
       this.cisUserInd = cisUserInd;
       this.cisUsers = cisUsers;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCnctFstNm() {
        return this.cnctFstNm;
    }
    
    public void setCnctFstNm(String cnctFstNm) {
        this.cnctFstNm = cnctFstNm;
    }
    public String getCnctLstNm() {
        return this.cnctLstNm;
    }
    
    public void setCnctLstNm(String cnctLstNm) {
        this.cnctLstNm = cnctLstNm;
    }
    public String getAutoSysId() {
        return this.autoSysId;
    }
    
    public void setAutoSysId(String autoSysId) {
        this.autoSysId = autoSysId;
    }
    public String getCnctOfflTtlNm() {
        return this.cnctOfflTtlNm;
    }
    
    public void setCnctOfflTtlNm(String cnctOfflTtlNm) {
        this.cnctOfflTtlNm = cnctOfflTtlNm;
    }
    public String getCnctPhNbr() {
        return this.cnctPhNbr;
    }
    
    public void setCnctPhNbr(String cnctPhNbr) {
        this.cnctPhNbr = cnctPhNbr;
    }
    public String getCnctPhExtNbr() {
        return this.cnctPhExtNbr;
    }
    
    public void setCnctPhExtNbr(String cnctPhExtNbr) {
        this.cnctPhExtNbr = cnctPhExtNbr;
    }
    public String getCnctPhFaxNbr() {
        return this.cnctPhFaxNbr;
    }
    
    public void setCnctPhFaxNbr(String cnctPhFaxNbr) {
        this.cnctPhFaxNbr = cnctPhFaxNbr;
    }
    public String getCnctPhAltNbr() {
        return this.cnctPhAltNbr;
    }
    
    public void setCnctPhAltNbr(String cnctPhAltNbr) {
        this.cnctPhAltNbr = cnctPhAltNbr;
    }
    public String getAddrInetDn() {
        return this.addrInetDn;
    }
    
    public void setAddrInetDn(String addrInetDn) {
        this.addrInetDn = addrInetDn;
    }
    public String getAddrInetWebDn() {
        return this.addrInetWebDn;
    }
    
    public void setAddrInetWebDn(String addrInetWebDn) {
        this.addrInetWebDn = addrInetWebDn;
    }
    public String getLin1OptAddr() {
        return this.lin1OptAddr;
    }
    
    public void setLin1OptAddr(String lin1OptAddr) {
        this.lin1OptAddr = lin1OptAddr;
    }
    public String getLin2OptAddr() {
        return this.lin2OptAddr;
    }
    
    public void setLin2OptAddr(String lin2OptAddr) {
        this.lin2OptAddr = lin2OptAddr;
    }
    public String getLin3OptAddr() {
        return this.lin3OptAddr;
    }
    
    public void setLin3OptAddr(String lin3OptAddr) {
        this.lin3OptAddr = lin3OptAddr;
    }
    public String getCityNm() {
        return this.cityNm;
    }
    
    public void setCityNm(String cityNm) {
        this.cityNm = cityNm;
    }
    public String getStCd() {
        return this.stCd;
    }
    
    public void setStCd(String stCd) {
        this.stCd = stCd;
    }
    public String getZipCd() {
        return this.zipCd;
    }
    
    public void setZipCd(String zipCd) {
        this.zipCd = zipCd;
    }
    public String getCtryIsoCd() {
        return this.ctryIsoCd;
    }
    
    public void setCtryIsoCd(String ctryIsoCd) {
        this.ctryIsoCd = ctryIsoCd;
    }
    public String getUserPwrdDn() {
        return this.userPwrdDn;
    }
    
    public void setUserPwrdDn(String userPwrdDn) {
        this.userPwrdDn = userPwrdDn;
    }
    public Date getUserPwrdLstUpdtDt() {
        return this.userPwrdLstUpdtDt;
    }
    
    public void setUserPwrdLstUpdtDt(Date userPwrdLstUpdtDt) {
        this.userPwrdLstUpdtDt = userPwrdLstUpdtDt;
    }
    public String getCoNm() {
        return this.coNm;
    }
    
    public void setCoNm(String coNm) {
        this.coNm = coNm;
    }
    public Date getUserPwrdExprDt() {
        return this.userPwrdExprDt;
    }
    
    public void setUserPwrdExprDt(Date userPwrdExprDt) {
        this.userPwrdExprDt = userPwrdExprDt;
    }
    public Date getUserAcssLstDt() {
        return this.userAcssLstDt;
    }
    
    public void setUserAcssLstDt(Date userAcssLstDt) {
        this.userAcssLstDt = userAcssLstDt;
    }
    public Date getUserAcssFstDt() {
        return this.userAcssFstDt;
    }
    
    public void setUserAcssFstDt(Date userAcssFstDt) {
        this.userAcssFstDt = userAcssFstDt;
    }
    public String getAddrInetLstDn() {
        return this.addrInetLstDn;
    }
    
    public void setAddrInetLstDn(String addrInetLstDn) {
        this.addrInetLstDn = addrInetLstDn;
    }
    public String getSwInetDn() {
        return this.swInetDn;
    }
    
    public void setSwInetDn(String swInetDn) {
        this.swInetDn = swInetDn;
    }
    public String getAcctUserDfltId() {
        return this.acctUserDfltId;
    }
    
    public void setAcctUserDfltId(String acctUserDfltId) {
        this.acctUserDfltId = acctUserDfltId;
    }
    public String getUserAddId() {
        return this.userAddId;
    }
    
    public void setUserAddId(String userAddId) {
        this.userAddId = userAddId;
    }
    public Date getAddDt() {
        return this.addDt;
    }
    
    public void setAddDt(Date addDt) {
        this.addDt = addDt;
    }
    public Date getCommUserAddDt() {
        return this.commUserAddDt;
    }
    
    public void setCommUserAddDt(Date commUserAddDt) {
        this.commUserAddDt = commUserAddDt;
    }
    public Date getCommRtnDt() {
        return this.commRtnDt;
    }
    
    public void setCommRtnDt(Date commRtnDt) {
        this.commRtnDt = commRtnDt;
    }
    public String getCommRtnDn() {
        return this.commRtnDn;
    }
    
    public void setCommRtnDn(String commRtnDn) {
        this.commRtnDn = commRtnDn;
    }
    public String getUserIiInd() {
        return this.userIiInd;
    }
    
    public void setUserIiInd(String userIiInd) {
        this.userIiInd = userIiInd;
    }
    public String getSrvcLvlAcssInd() {
        return this.srvcLvlAcssInd;
    }
    
    public void setSrvcLvlAcssInd(String srvcLvlAcssInd) {
        this.srvcLvlAcssInd = srvcLvlAcssInd;
    }
    public String getLockInd() {
        return this.lockInd;
    }
    
    public void setLockInd(String lockInd) {
        this.lockInd = lockInd;
    }
    public Date getLockDt() {
        return this.lockDt;
    }
    
    public void setLockDt(Date lockDt) {
        this.lockDt = lockDt;
    }
    public String getUserLockLstId() {
        return this.userLockLstId;
    }
    
    public void setUserLockLstId(String userLockLstId) {
        this.userLockLstId = userLockLstId;
    }
    public String getLockDn() {
        return this.lockDn;
    }
    
    public void setLockDn(String lockDn) {
        this.lockDn = lockDn;
    }
    public String getAcctUserIiId() {
        return this.acctUserIiId;
    }
    
    public void setAcctUserIiId(String acctUserIiId) {
        this.acctUserIiId = acctUserIiId;
    }
    public String getUserIdUc() {
        return this.userIdUc;
    }
    
    public void setUserIdUc(String userIdUc) {
        this.userIdUc = userIdUc;
    }
    public BigDecimal getCmaPrimRoleNbr() {
        return this.cmaPrimRoleNbr;
    }
    
    public void setCmaPrimRoleNbr(BigDecimal cmaPrimRoleNbr) {
        this.cmaPrimRoleNbr = cmaPrimRoleNbr;
    }
    public String getSelListDupChkInd() {
        return this.selListDupChkInd;
    }
    
    public void setSelListDupChkInd(String selListDupChkInd) {
        this.selListDupChkInd = selListDupChkInd;
    }
    public char getDupChkInd() {
        return this.dupChkInd;
    }
    
    public void setDupChkInd(char dupChkInd) {
        this.dupChkInd = dupChkInd;
    }
    public String getCisUserInd() {
        return this.cisUserInd;
    }
    
    public void setCisUserInd(String cisUserInd) {
        this.cisUserInd = cisUserInd;
    }
    public Set<CisUser> getCisUsers() {
        return this.cisUsers;
    }
    
    public void setCisUsers(Set<CisUser> cisUsers) {
        this.cisUsers = cisUsers;
    }




}


