package com.ibg.selectionrecords.pojo;

// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CisCustomer generated by hbm2java
 */
public class CisCustomer implements java.io.Serializable {

	private String customerNo;
	private String currency;
	private String custGroup;
	private String division;
	private String reportName;
	private BigDecimal yearEnd;

	public CisCustomer() {
	}

	public CisCustomer(String customerNo) {
		this.customerNo = customerNo;
	}

	public CisCustomer(String customerNo, String currency, String custGroup,
			String division, String reportName, BigDecimal yearEnd) {
		this.customerNo = customerNo;
		this.currency = currency;
		this.custGroup = custGroup;
		this.division = division;
		this.reportName = reportName;
		this.yearEnd = yearEnd;
	}

	public String getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(String customerNo) {
		this.customerNo = customerNo;
	}

	/*
	 * public Map<String, CisUser> getUsers(){return users;} public void
	 * setUsers(Map<String, CisUser> users){this.users = users;} private
	 * Map<String, CisUser> users;
	 */
	public Set<CisUser> getUsers() {
		return users;
	}

	public void setUsers(Set<CisUser> users) {
		this.users = users;
	}

	private Set<CisUser> users = new HashSet<CisUser>();

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getCustGroup() {
		return this.custGroup;
	}

	public void setCustGroup(String custGroup) {
		this.custGroup = custGroup;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getReportName() {
		return this.reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public BigDecimal getYearEnd() {
		return this.yearEnd;
	}

	public void setYearEnd(BigDecimal yearEnd) {
		this.yearEnd = yearEnd;
	}

}
