package com.ibg.selectionrecords.pojo;
// Generated Nov 14, 2013 3:33:55 PM by Hibernate Tools 3.2.1.GA



/**
 * CisCustGroup generated by hbm2java
 */
public class CisCustGroup  implements java.io.Serializable {


     private String custGroup;
     private String allowstockrush;
     private String ccgroupsoptin;
     private String country;
     private String displayebookestnet;
     private String displayestnet;
     private String displayreviews;
     private String ifound;
     private String libraryGroup;
     private int maximumorderquantity;
     private String multiline;
     private String ilsSystem;
     private String openurl;
     private String reportName;
     private String restrictinitials;
     private String retainselector;
     private String showfund;
     private String showlocation;
     private String showprofile;
     private String shibblolethentityid;
     private String shibbolethidp;
     private String shibbolethurl;

    public CisCustGroup() {
    }

	
    public CisCustGroup(String custGroup, int maximumorderquantity) {
        this.custGroup = custGroup;
        this.maximumorderquantity = maximumorderquantity;
    }
    public CisCustGroup(String custGroup, String allowstockrush, String ccgroupsoptin, String country, String displayebookestnet, String displayestnet, String displayreviews, String ifound, String libraryGroup, int maximumorderquantity, String multiline, String ilsSystem, String openurl, String reportName, String restrictinitials, String retainselector, String showfund, String showlocation, String showprofile, String shibblolethentityid, String shibbolethidp, String shibbolethurl) {
       this.custGroup = custGroup;
       this.allowstockrush = allowstockrush;
       this.ccgroupsoptin = ccgroupsoptin;
       this.country = country;
       this.displayebookestnet = displayebookestnet;
       this.displayestnet = displayestnet;
       this.displayreviews = displayreviews;
       this.ifound = ifound;
       this.libraryGroup = libraryGroup;
       this.maximumorderquantity = maximumorderquantity;
       this.multiline = multiline;
       this.ilsSystem = ilsSystem;
       this.openurl = openurl;
       this.reportName = reportName;
       this.restrictinitials = restrictinitials;
       this.retainselector = retainselector;
       this.showfund = showfund;
       this.showlocation = showlocation;
       this.showprofile = showprofile;
       this.shibblolethentityid = shibblolethentityid;
       this.shibbolethidp = shibbolethidp;
       this.shibbolethurl = shibbolethurl;
    }
   
    public String getCustGroup() {
        return this.custGroup;
    }
    
    public void setCustGroup(String custGroup) {
        this.custGroup = custGroup;
    }
    public String getAllowstockrush() {
        return this.allowstockrush;
    }
    
    public void setAllowstockrush(String allowstockrush) {
        this.allowstockrush = allowstockrush;
    }
    public String getCcgroupsoptin() {
        return this.ccgroupsoptin;
    }
    
    public void setCcgroupsoptin(String ccgroupsoptin) {
        this.ccgroupsoptin = ccgroupsoptin;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getDisplayebookestnet() {
        return this.displayebookestnet;
    }
    
    public void setDisplayebookestnet(String displayebookestnet) {
        this.displayebookestnet = displayebookestnet;
    }
    public String getDisplayestnet() {
        return this.displayestnet;
    }
    
    public void setDisplayestnet(String displayestnet) {
        this.displayestnet = displayestnet;
    }
    public String getDisplayreviews() {
        return this.displayreviews;
    }
    
    public void setDisplayreviews(String displayreviews) {
        this.displayreviews = displayreviews;
    }
    public String getIfound() {
        return this.ifound;
    }
    
    public void setIfound(String ifound) {
        this.ifound = ifound;
    }
    public String getLibraryGroup() {
        return this.libraryGroup;
    }
    
    public void setLibraryGroup(String libraryGroup) {
        this.libraryGroup = libraryGroup;
    }
    public int getMaximumorderquantity() {
        return this.maximumorderquantity;
    }
    
    public void setMaximumorderquantity(int maximumorderquantity) {
        this.maximumorderquantity = maximumorderquantity;
    }
    public String getMultiline() {
        return this.multiline;
    }
    
    public void setMultiline(String multiline) {
        this.multiline = multiline;
    }
    public String getIlsSystem() {
        return this.ilsSystem;
    }
    
    public void setIlsSystem(String ilsSystem) {
        this.ilsSystem = ilsSystem;
    }
    public String getOpenurl() {
        return this.openurl;
    }
    
    public void setOpenurl(String openurl) {
        this.openurl = openurl;
    }
    public String getReportName() {
        return this.reportName;
    }
    
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }
    public String getRestrictinitials() {
        return this.restrictinitials;
    }
    
    public void setRestrictinitials(String restrictinitials) {
        this.restrictinitials = restrictinitials;
    }
    public String getRetainselector() {
        return this.retainselector;
    }
    
    public void setRetainselector(String retainselector) {
        this.retainselector = retainselector;
    }
    public String getShowfund() {
        return this.showfund;
    }
    
    public void setShowfund(String showfund) {
        this.showfund = showfund;
    }
    public String getShowlocation() {
        return this.showlocation;
    }
    
    public void setShowlocation(String showlocation) {
        this.showlocation = showlocation;
    }
    public String getShowprofile() {
        return this.showprofile;
    }
    
    public void setShowprofile(String showprofile) {
        this.showprofile = showprofile;
    }
    public String getShibblolethentityid() {
        return this.shibblolethentityid;
    }
    
    public void setShibblolethentityid(String shibblolethentityid) {
        this.shibblolethentityid = shibblolethentityid;
    }
    public String getShibbolethidp() {
        return this.shibbolethidp;
    }
    
    public void setShibbolethidp(String shibbolethidp) {
        this.shibbolethidp = shibbolethidp;
    }
    public String getShibbolethurl() {
        return this.shibbolethurl;
    }
    
    public void setShibbolethurl(String shibbolethurl) {
        this.shibbolethurl = shibbolethurl;
    }




}


